export interface IPersonModel {
    id:string,
    fullName:string,
    dob:string,
    age:string,
    profession:string,
    address:{
        street:string,
        city:string,
        state:string,
        zipCode:string
    },
    preferences:{
        subscription:boolean,
        language:string,
        contactMethod:string,
        email:string,
        phno:string
    },
    image:string
}
